# Generated by Django 4.1.3 on 2022-12-19 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('ชาย', 'ชาย'), ('หญิง', 'หญิง')], default='ชาย', max_length=6)),
                ('birthdate', models.DateField()),
                ('department', models.CharField(choices=[('กราฟิก', 'กราฟิก'), ('ไอที', 'ไอที'), ('บัญชี', 'บัญชี')], default='กราฟิก', max_length=50)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
