# Generated by Django 4.1.3 on 2022-12-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
